# Generated by Django 5.2.4 on 2025-07-28 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mission_type', models.CharField(max_length=255)),
                ('crew', models.CharField(max_length=255)),
                ('launch', models.DateField()),
                ('splash_down', models.DateField()),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='missions/images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.historicalmission')),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_cover', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mission_type', models.CharField(max_length=255)),
                ('crew_size', models.IntegerField()),
                ('launch', models.DateField()),
                ('duration', models.IntegerField()),
                ('thoughts', models.CharField(max_length=255)),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingMissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_image', models.ImageField(upload_to='missions/images/')),
                ('crew_name', models.CharField(blank=True, max_length=255)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.upcomingmission')),
            ],
        ),
        migrations.DeleteModel(
            name='Population',
        ),
    ]
