# Generated by Django 5.2.4 on 2025-07-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_historicalmission_historicalmissionimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmission',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='upcomingmission',
            name='thoughts',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
