# Generated by Django 5.2.4 on 2025-07-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_upcomingmission_user_missionthought'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('introduction', models.TextField()),
                ('namesake', models.TextField()),
                ('potential', models.TextField()),
                ('metrics', models.TextField()),
                ('moons', models.CharField(max_length=255)),
                ('rings', models.CharField(max_length=255)),
                ('rotation', models.TextField()),
                ('formation', models.TextField()),
                ('structure', models.TextField()),
                ('atmosphere', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='missions/images/')),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
