# Generated by Django 5.2.4 on 2025-07-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_planet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spacecraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mission', models.TextField()),
                ('launch_date', models.DateField()),
                ('operator', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='missions/images/')),
            ],
        ),
    ]
