# Generated by Django 5.2.4 on 2025-08-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_spacecraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('net', models.DateTimeField()),
                ('image', models.URLField(blank=True, null=True)),
                ('mission_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mission_description', models.TextField(blank=True, null=True)),
                ('mission_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rocket_name', models.CharField(blank=True, max_length=100, null=True)),
                ('rocket_family', models.CharField(blank=True, max_length=100, null=True)),
                ('rocket_variant', models.CharField(blank=True, max_length=100, null=True)),
                ('isp', models.IntegerField(blank=True, null=True)),
                ('launch_service_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('pad_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location_name', models.CharField(blank=True, max_length=100, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
