# Generated by Django 5.2.4 on 2025-08-04 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_launch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('type', models.CharField(choices=[('suggestion', 'General Suggestion'), ('satellite', 'Satellite Mission'), ('manned', 'Manned Mission'), ('unmanned', 'Unmanned Mission'), ('research', 'Research Mission'), ('other', 'Other')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='missions/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='missions/images/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
